services:
  client:
    container_name: client
    image: kim015jh/hana-store-client
    build: 
      context: ./
      dockerfile: apps/client/Dockerfile
    networks:
      - client-connect
    
  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    restart: always
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/default.conf:/etc/nginx/templates/default.conf.template
      - .${SSL_CERTIFICATE_CHAIN}:${SSL_CERTIFICATE_CHAIN}
      - .${SSL_CERTIFICATE_KEY}:${SSL_CERTIFICATE_KEY}
    networks:
      - client-connect
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
      - SERVER_DOMAIN_NAME=${SERVER_DOMAIN_NAME}
      - CLIENT_PORT=${CLIENT_PORT}
      - SSL_CERTIFICATE_CHAIN=${SSL_CERTIFICATE_CHAIN}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}      
    depends_on:
      - client
  
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${SERVER_DOMAIN_NAME}
    volumes:
      - ./etc/certbot/conf:/etc/letsencrypt:rw
      - ./etc/certbot/logs:/var/log/letsencrypt:rw
      - ./etc/certbot/data:/var/www/certbot:rw

networks:
  client-connect:
    driver: bridge
    