version: "3.9"
services:
  client:
    container_name: client
    image: kim015jh/hana-store-client
    build: 
      context: ./
      dockerfile: apps/client/Dockerfile
    networks:
      - client-connect
  
  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    restart: always
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/default.conf:/etc/nginx/templates/default.conf.template
      - ./etc/nginx/ssl/${SSL_CERTIFICATE_CHAIN}:/etc/nginx/ssl/${SSL_CERTIFICATE_CHAIN}
      - ./etc/nginx/ssl/${SSL_CERTIFICATE_KEY}:/etc/nginx/ssl/${SSL_CERTIFICATE_KEY}
    networks:
      - client-connect
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
      - SERVER_DOMAIN_NAME=${SERVER_DOMAIN_NAME}
      - CLIENT_PORT=${CLIENT_PORT}
      - SSL_CERTIFICATE_CHAIN=${SSL_CERTIFICATE_CHAIN}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}      
    depends_on:
      - client

networks:
  client-connect:
    driver: bridge
    