version: "3.9"
services:
  client:
    container_name: client
    image: hana-store/client
    build: 
      context: ./
      dockerfile: apps/client/Dockerfile
    networks:
      - client-connect
  
  nginx:
    container_name: nginx
    image: hana-store/nginx
    restart: always
    build:
      dockerfile: etc/nginx/Dockerfile
    networks:
      - client-connect
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - client

networks:
  client-connect:
    driver: bridge