import { Inter } from 'next/font/google';

import type { Metadata } from 'next';

import './styles/app.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Hana Store',
  description: 'Generated by hwanfront',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='kr'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
