name: format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/main.yml
      - name: format
        run: pnpm run prettier
