name: Setup

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: 9
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install -D --frozen-lockfile
      - name: Run eslint with client
        run: pnpm run client lint:changed
      - name: Run eslint with ui
        run: pnpm run ui lint:changed
      - name: Run prettier
        run: pnpm run prettier
